### ISSUE TITLE
Enumerable#min_by method signature of Ruby Core changed

### ISSUE THREAD

**Issue by codez** [blackwinter/nuggets#4]
In Nugget, Enumerable#min_by takes exactly on argument. In Ruby Core, Enumerable#min_by (from 1.9.3 upwards), takes zero arguments but an optional block. The same is for #max_by and possibly for other methods from Ruby Core as well.

Code relying on the Ruby Core signatures fail if Nuggets is used in a project (wrong number of arguments (0 for 1)).

**Comment by blackwinter** [comment]
Yes, that's right, compatibility with core methods is definitely an issue here and I'm sorry it broke your code. I've fixed it now. Could you check the [prerelease](https://rubygems.org/gems/nuggets/versions/1.2.1.pre1) to see if it works?

**Comment by codez** [comment]
Thanks, these works for me.

**Comment by blackwinter** [comment]
Great! Version 1.2.1 is released.

**Comment by codez** [comment]
Oops, my initial testing was not that thorough obviously. `_nuggets_original_min_by(by, &block)` still fails with "wrong number of arguments (1 for 0)", as the original method from Ruby core takes no arguments.

**Comment by blackwinter** [comment]
Well, Ruby 2.2 did actually introduce an optional argument for `#min_by` and `#max_by`; that's the version I checked against. But I don't think there's much we can do. When these methods were introduced in `nuggets` they didn't exist in core; and now they even have different signatures across versions. There's always a risk when reopening core classes.

Maybe we should rather talk about your code and why there are/need to be uses of both the original core behaviour and the monkey-patched behaviour from `nuggets`. The latter is merely for convenience and can be easily replaced with core methods.

**Comment by codez** [comment]
Ok. I guess I messed up with spring and stuff. Cannot reproduce anymore. Sorry for the inconvenience.
